steps:
  # 0. ASEGURAR QUE EL REPOSITORIO DE ARTIFACT REGISTRY EXISTA
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories describe ms-motor-responsabilidad1 --location=us-east1 || \
        gcloud artifacts repositories create ms-motor-responsabilidad1 --repository-format=docker --location=us-east1

  # 1. CONSTRUCCIÓN DE LA IMAGEN DOCKER
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad1/motor-img:$COMMIT_SHA',
      '.'
    ]

  # 2. PUSH DE LA IMAGEN AL REPOSITORIO
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad1/motor-img:$COMMIT_SHA' ]

  # 3. DESPLIEGUE DEL SERVICIO PRINCIPAL (CLOUD RUN)
  # Se eliminaron los jobs y se configuraron 4Gi de RAM para evitar reinicios por OOM
  - id: "deploy-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy ia-mv-motor-responsabilidadv1 \
          --region us-east1 \
          --image us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad1/motor-img:$COMMIT_SHA \
          --cpu 2 \
          --memory 4Gi \
          --set-env-vars PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=bucket-motor-responsabilidad,APP_ENV=sbx \
          --labels billing-tag=ia-mv-motor-responsabilidadv1,vp=patrimoniales,team=movilidad,tipo=proyecto \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad1/motor-img:$COMMIT_SHA'